config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	resources :hospitals
	get 'search', to: 'hospitals#search', as: 'search'
	get 'map', to: 'map#index', as: 'maps'
	# get 'about' => 'users#about', as: 'about'
	root 'hospitals#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hospital.rb
class Hospital < ApplicationRecord

	has_many :practice_times, inverse_of: :hospital
	has_many :pethospitals
	has_many :pets, :through => :pethospitals
	has_many :days, :through => :pethospitals
    accepts_nested_attributes_for :practice_times, reject_if: :all_blank, allow_destroy: true
    attachment :hospital_image
	geocoded_by :address
	after_validation :geocode, if: :address_changed?

	validates :name, presence: true
	validates :address, presence: true
	validates :tel, presence: true
	# validates :pet_ids, presence: true
	# validates :day_ids, presence: true
	# 国内プレフィックス(0)と市外局番(1～4) – 市内局番(1～4) – 加入者番号(4)
	# ハイフンはありでもなしでも可。全体の桁数チェックは無し
	VALID_PHONE_REGEX = /\A(0{1}\d{1,4}-{0,1}\d{1,4}-{0,1}\d{4})\z/
	validates :tel, presence: true, format: { with: VALID_PHONE_REGEX }

	private

	def before_validations
    # telの文字列から先頭と末尾のスペースを除去する
    tel.strip!
	end
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  before_action :set_hospital, only: [:show, :edit, :update, :destroy]
  before_action :admin_user,　only: [:new, :create, :edit, :update, :destroy],except: [:top, :show, :index, :search]

  def top
  end

  def search
    @search = Hospital.ransack(params[:q])
    @results = @search.result.includes(:days, :pets).page(params[:page])
    @pets = Pet.all
    @days = Day.all
  end

  def index
    @hospitals = Hospital.page(params[:page])
  end

  def show
    @practice_time = @hospital.practice_times
    @hash = Gmaps4rails.build_markers(@hospital) do |hospital, marker|
      marker.lat hospital.latitude
      marker.lng hospital.longitude
      marker.infowindow render_to_string(partial: "hospitals/infowindow", locals: { hospital: hospital })
    end
  end

  def new
    @hospital = Hospital.new
    @practice_time = @hospital.practice_times.build
  end

  def edit
  end

  def create
    @hospital = Hospital.new(hospital_params)

    respond_to do |format|
      if @hospital.save
        format.html { redirect_to @hospital, notice: 'Hospital was successfully created.' }
        format.json { render :show, status: :created, location: @hospital }
      else
        format.html { render :new }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @hospital.update(hospital_params)
        format.html { redirect_to @hospital, notice: 'Hospital was successfully updated.' }
        format.json { render :show, status: :ok, location: @hospital }
      else
        format.html { render :edit }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @hospital.destroy
    respond_to do |format|
      format.html { redirect_to hospitals_url, notice: 'Hospital was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_hospital
    @hospital = Hospital.find(params[:id])
  end

  def hospital_params
    params.require(:hospital).permit( :name, :address, :latitude, :longitude, :tel, :hospital_image, pet_ids: [], day_ids: [], practice_times_attributes: [:id, :start_time, :end_time, :_destroy])
  end

  def search_params
    params.require(:q).permit(:name_cont, :address_cont, :pets_id_eq, :days_id_in)
  end

  def admin_user
    if user_signed_in?
     unless current_user.admin == true
      redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/views/hospitals/_form.html.erb
<%= form_for(hospital) do |f| %>
<% if hospital.errors.any? %>
<div id="error_explanation">
  <h5 class="alert alert-danger" role="alert">エラーが<%= pluralize(hospital.errors.count, "件") %>あります。</h5>

  <ul>
    <% hospital.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<form>
  <div class="field form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", placeholder: "病院名を入力" %>
  </div>

  <div class="field form-group">
    <%= f.label "イメージ画像を選択" %>
    <%= f.attachment_field :hospital_image %>
  </div>


  <div class="form-group">
    <label>診療対象動物</label><br>
    <%= f.collection_check_boxes :pet_ids, Pet.all, :id, :name, include_hidden: false %>
  </div>

  <div class="form-group">
    <label>診療日</label><br>
    <%= f.collection_check_boxes :day_ids, Day.all, :id, :name, include_hidden: false %>
  </div>

  <div class="field form-group">
    <%= f.label :tel %>
    <%= f.text_field :tel, class: "form-control", placeholder: "ハイフンあり/なし数字を入力" %>
  </div>

  <div class="field form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control", placeholder: "住所を入力" %>
  </div>

  <div class="field form-group">
    <%= f.label :latitude %>
    <%= f.text_field :latitude, class: "form-control", placeholder: "緯度を入力" %>
  </div>

  <div class="field form-group">
    <%= f.label :longitude %>
    <%= f.text_field :longitude, class: "form-control", placeholder: "経度を入力" %>
  </div>

  <div class="field form-group">
    <%= f.label "診療時間" %><br>
    <%= f.fields_for :practice_times do |time| %>

    <%= render 'practice_time_fields', f: time %>

    <% end %>
    <div id="links">
      <%= link_to_add_association '項目の追加', f, :practice_times %>
    </div>

    <div style="margin: 30px 0;">
      <%= f.submit class: "submit-button center-block" %>
      <% end %>
    </div>

  </form>

app/views/hospitals/_infowindow.html.erb
<div class="container-fluid">
	<div class="row">
		<%= attachment_image_tag hospital, :hospital_image, :fill, 150, 150, format: 'jpeg', fallback: "/images/noimage.jpg", :size => "150x150", class: "center-block" %>

		病院名：<%= link_to hospital.name, hospital_path(hospital) %><br>
		住所：<%= hospital.address %><br>

		<%= link_to "この施設へ行く" ,"https://www.google.com/maps/dir/?api=1&destination=#{hospital.latitude},#{hospital.longitude}",target: "_blank" %>
	</div>
</div>

app/views/hospitals/_practice_time_fields.html.erb
<div class="nested-fields">
	<div class="form-group">
		<%= f.time_select :start_time, { :minute_step => 15 } %>～
		<%= f.time_select :end_time, { :minute_step => 15 } %>
		<%= link_to_remove_association "削除", f %>
	</div>
</div>

app/views/hospitals/_result.html.erb
<div class="row">
    <div class="table-responsive">
        <table class="table table-striped background-content" >
            <thead>
                <tr>
                    <th class="col-sm-2"></th>
                    <th class="col-sm-2">病院名</th>
                    <th class="col-sm-1">診療日</th>
                    <th class="col-sm-2">診療時間</th>
                    <th class="col-sm-2">住所</th>
                    <th class="col-sm-1">診療動物</th>
                    <% if current_user.try(:admin?) %>
                    <th class="col-sm-1">緯度・経度</th>
                    <% end %>
                    <th class="col-sm-1"></th>
                </tr>
            </thead>
            <tbody>
                <% results.each do |result| %>
                <tr>
                    <td>
                        <%= attachment_image_tag result, :hospital_image, :fill, 100, 100, format: 'jpeg', fallback: "/images/noimage.jpg", :size => "100x100", class: "center-block" %>
                    </td>
                    <td>
                        <%= result.name %>
                    </td>
                    <td>
                        <% result.days.each do |day| %>
                        <div class="badge badge-orange">
                            <%= day.name %>
                        </div>
                        <% end %>
                    </td>
                    <td>
                        <% result.practice_times.each do |time| %>
                        <%= time.start_time.to_s(:time) %> ～
                        <%= time.end_time.to_s(:time) %><br>
                        <% end %>
                    </td>
                    <td>
                        <%= result.address %>
                    </td>
                    <td>
                        <% result.pets.each do |pet| %>
                        <div class="badge badge-pink">
                            <%= pet.name %>
                        </div>
                        <% end %>
                    </td>
                    <% if current_user.try(:admin?) %>
                    <td>
                        緯度：<%= result.latitude %><br>
                        経度：<%= result.longitude %>
                    </td>
                    <% end %>
                    <td>
                        <div class="table-btn">
                            <%= link_to '詳細', result, class: "cp_primary" %>
                            <% if current_user.try(:admin?) %>
                            <%= link_to '編集', edit_hospital_path(result), class: "cp_success" %>
                            <%= link_to '削除', result, method: :delete, data: { confirm: '削除しますか?' }, class: "cp_destroy" %>
                            <% end %>
                        </div>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>

        <div class="pagination">
            <%= paginate @results , class: "pagenate" %>
        </div>

    </div>
</div>

app/views/hospitals/_search.html.erb
    <%= search_form_for(search, url:search_path)  do |f| %>

    <div class="row">
      <div class="col-xs-offset-1 col-xs-10 col-sm-offset-2 col-sm-8">
        <div class="search-box background-content">
          <h2 class="hos-mb-50">病院検索</h2>

          <div class="form-group form-text">
            <%= f.label :name_cont %>
            <%= f.text_field :name_cont, class: "form-control" %>
          </div>

          <div class="form-group form-text">
            <%= f.label :address_cont %>
            <%= f.text_field :address_cont, class: "form-control" %>
          </div>

          <div class="field form-group">
            <label>診療対象動物</label><br>
            <label><%= f.radio_button 'pets_id_eq', '', {:checked => true} %> 指定なし</label>
            <%= f.collection_radio_buttons :pets_id_eq, @pets, :id, :name, include_hidden: false %>
          </div>

          <div class="field form-group">
            <label>診療日</label><br>
            <label><%= f.radio_button 'days_id_eq', '', {:checked => true} %> 指定なし</label>
            <%= f.collection_radio_buttons :days_id_eq, @days, :id, :name, include_hidden: false %>
          </div>

          <%= f.button fa_icon("search", text: "検索する"), class: "submit-button center-block" %>

        </div>
      </div>
    </div>

    <% end %>

app/views/hospitals/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-offset-1 col-xs-10 col-sm-offset-2 col-sm-8 background-content">
			<h1>登録病院情報編集</h1>

			<%= render 'form', hospital: @hospital %>

			<%= link_to '詳細', @hospital, class: "btn btn-warning" %>
			<%= link_to '一覧', hospitals_path, class: "btn btn-primary" %>
		</div>
	</div>
</div>

app/views/hospitals/index.html.erb
<div class="container">
    <div class="row">
        <p id="notice"><%= notice %></p>

        <h1>病院一覧</h1>

        <div class="hos-button">
          <% if current_user.try(:admin?) %>
          <%= link_to '病院を追加する', new_hospital_path, class: "btn btn-primary" %>
          <% end %>
      </div>

          <div class="table-responsive">
            <table class="table table-striped background-content" >
                <thead>
                    <tr>
                        <th class="col-xs-2 col-sm-2"></th>
                        <th class="col-xs-1 col-sm-2">病院名</th>
                        <th class="col-xs-1 col-sm-1">診療日</th>
                        <th class="col-xs-2 col-sm-2">診療時間</th>
                        <th class="col-xs-2 col-sm-2">住所</th>
                        <th class="col-xs-1 col-sm-1">診療動物</th>
                        <% if current_user.try(:admin?) %>
                        <th class="col-xs-1 col-sm-1">緯度・経度</th>
                        <% end %>
                        <th class="col-xs-1 col-sm-1"></th>
                    </tr>
                </thead>
                <tbody>
                    <% @hospitals.each do |hospital| %>
                    <tr>
                        <td>
                            <%= attachment_image_tag hospital, :hospital_image, :fill, 100, 100, format: 'jpeg', fallback: "/images/noimage.jpg", :size => "100x100", class: "center-block" %>
                        </td>
                        <td>
                            <%= hospital.name %>
                        </td>
                        <td>
                            <% hospital.days.each do |day| %>
                            <div class="badge badge-orange">
                                <%= day.name %>
                            </div><br>
                            <% end %>
                        </td>
                        <td>
                            <% hospital.practice_times.each do |time| %>
                            <%= time.start_time.to_s(:time) %> ～
                            <%= time.end_time.to_s(:time) %><br>
                            <% end %>
                        </td>
                        <td>
                            <%= hospital.address %>
                        </td>
                        <td>
                            <% hospital.pets.each do |pet| %>
                            <div class="badge badge-pink">
                                <%= pet.name %>
                            </div><br>
                            <% end %>
                        </td>
                        <% if current_user.try(:admin?) %>
                        <td>
                            緯度：<%= hospital.latitude %><br>
                            経度：<%= hospital.longitude %>
                        </td>
                        <% end %>
                        <td>
                            <div class="table-btn">
                                <%= link_to '詳細', hospital, class: "cp_primary" %>
                                <% if current_user.try(:admin?) %>
                                <%= link_to '編集', edit_hospital_path(hospital), class: "cp_success" %>
                                <%= link_to '削除', hospital, method: :delete, data: { confirm: '削除しますか?' }, class: "cp_destroy" %>
                                <% end %>
                            </div>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <div class="pagination">
            <%= paginate @hospitals , class: "pagenate" %>
        </div>
    </div>
</div>

app/views/hospitals/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-offset-1 col-xs-10 col-sm-offset-2 col-sm-8 background-content">
			<h1>新規病院登録</h1>

			<%= render 'form', hospital: @hospital %>

			<%= link_to '病院一覧へ', hospitals_path %>
		</div>
	</div>
</div>

app/views/hospitals/search.html.erb
<div class="container">
  <div class="row">
    <p id="notice">
      <%= notice %>
    </p>

    <%= render 'search', search: @search %>

    <% if @results.any? %>
    <%= render 'result', results: @results %>
    <% else %>
    <div class="search-not-result">
      <h3>条件にあう検索結果はありませんでした。</h3>
      <% end %>
    </div>
  </div>
</div>

app/views/hospitals/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-offset-1 col-xs-10 col-sm-offset-2 col-sm-8 background-content">


      <h2 class="text-center hos-mt-30"><%= @hospital.name %></h2>

      <div class="row hos-mt-30">
        <div class="col-xs-12 col-sm-6  hos-mt-30">
          <%= attachment_image_tag @hospital, :hospital_image, :fill, 250, 250, format: 'jpeg', fallback: "/images/noimage.jpg", :size => "250x250", class: "center-block" %>
        </div>

        <div class="col-xs-12 col-sm-6 text-center">
          <div class="hos-mt-15">
            <span class="badge badge-orange">住所</span><br>
            <%= @hospital.address %>
          </div>

          <div class="hos-mt-15">
            <span class="badge badge-pill badge-orange">TEL</span><br>
            <%= @hospital.tel %>
          </div>

          <div class="hos-mt-15">
            <span class="badge badge-pill badge-orange">診療日</span><br>
            <% @hospital.days.each do |day| %>
            <span>(</span><%= day.name %><span>)</span>
            <% end %>
          </div>

          <div class="hos-mt-15">
            <span class="badge badge-pill badge-orange">診療時間</span><br>
            <% @practice_time.each do |time| %>
            <%= time.start_time.to_s(:time) %> ～
            <%= time.end_time.to_s(:time) %><br>
            <% end %>
          </div>

          <div class="hos-mt-15">
            <span class="badge badge-pill badge-orange">ペット種別</span><br>
            <% @hospital.pets.each do |pet| %>
            <%= pet.name %><span> </span>
            <% end %>
          </div>

          <% if current_user.try(:admin?) %>
          <div class="hos-mt-15">
            <span class="badge badge-pill badge-orange">緯度・経度</span><br>
            緯度：<%= @hospital.latitude %><br>
            経度：<%= @hospital.longitude %>
            <% end %>
          </div>
        </div>
      </div>

      <h2 class="text-center">アクセス</h2>
      <div class="row">
        <div class="col-xs-12">
          <div id="map"></div>
        </div>
      </div>

      <h2 class="text-center">近くにある病院</h2>

      <ul class="hos-mt-15">
        <% for @hospital in @hospital.nearbys(10) %>
        <li><%= link_to @hospital.name, @hospital %>
          (<%= @hospital.distance.round(2) %> km)</li>
          <% end %>
        </ul>

        <div class="col-xs-12 hos-button">
          <% if current_user.try(:admin?) %>
          <%= link_to '編集', edit_hospital_path(@hospital), class: "btn btn-success btn-color" %>
          <%= link_to '病院一覧へ', hospitals_path, class: "btn btn-warning" %>
          <% else %>
          <%= link_to '病院一覧へ', hospitals_path, class: "btn btn-warning" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <script>
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: { id: 'map' } }, function() {
      markers = handler.addMarkers(<%=raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      handler.getMap().setZoom(15);
    });
  </script>

app/views/hospitals/top.html.erb
<div class="top-background">
      <div class="container">
      	<div class="row">
      		<div class="col-xs-12 col-sm-7">
      		<br>
      		<br>
      		<br>
      		<br>
      		<br>
        <h1>ペットに合った病院を見つける</h1>
        <p>先に詳しい病院の条件を指定して探す。または現在地から近くの病院を素早く探すことが出来ます。</p>
        <br>
        <br>
        <br>
        <%= link_to '条件を指定して探す', search_path, class: "btn btn-primary btn-lg" %>
        <span>　</span>
        <%= link_to '現在地から探す', maps_path, class: "btn btn-warning btn-lg" %>
      </div>
  </div>
  </div>
</div>