config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	resources :hospitals
	get 'search', to: 'hospitals#search', as: 'search'
	get 'map', to: 'map#index', as: 'maps'
	# get 'about' => 'users#about', as: 'about'
	root 'hospitals#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Portfolio</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.rawgit.com/balzss/luxbar/ae5835e2/build/luxbar.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="//maps.google.com/maps/api/js?key=AIzaSyCvtHHxeUnGwM1eHb9OH3Vn5tGsuzmN5Ls"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
</head>

<body class="background">

  <!-- 固定ナビ -->
  <header id="luxbar" class="luxbar-fixed">
    <input type="checkbox" class="luxbar-checkbox" id="luxbar-checkbox"/>
    <div class="luxbar-menu luxbar-menu-right luxbar-menu-material-amber">
      <ul class="luxbar-navigation">
        <li class="luxbar-header">
          <a href="#" class="luxbar-brand">PET SEARCH</a>
          <label class="luxbar-hamburger luxbar-hamburger-doublespin"
          id="luxbar-hamburger" for="luxbar-checkbox"> <span></span> </label>
        </li>
        <li class="luxbar-item"><%= link_to " HOME", root_path, class: "fa fa-home" %></li>
        <li class="luxbar-item"><%= link_to " HOSPITAL", hospitals_path, class: "fa fa-hospital" %></li>
        <li class="luxbar-item"><%= link_to " SEARCH", search_path, class: "fa fa-search" %></li>
        <li class="luxbar-item"><%= link_to " MAP", maps_path, class: "fa fa-map" %></li>
        <li class="luxbar-item">
          <% if user_signed_in? %>
          <%= link_to " SIGN-OUT", destroy_user_session_path, method: :delete, class: "fa fa-sign-out" %>
          <% else %>
          <%= link_to " SIGN-IN", new_user_session_path, class: "fa fa-sign-in" %>
          <% end %>
        </li>
      </ul>
    </div>
  </header>

    <%= yield %>

</body>

</html>